2021/03/24 17:28:10 [crit] 31#31: *1 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 17:28:10 [crit] 31#31: *1 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 17:28:10 [crit] 31#31: *1 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 17:28:10 [crit] 31#31: *1 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 17:28:11 [crit] 31#31: *1 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 17:28:11 [crit] 31#31: *1 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 17:28:12 [crit] 31#31: *1 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 17:28:12 [crit] 31#31: *1 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 17:28:12 [crit] 31#31: *1 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 17:28:12 [crit] 31#31: *1 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 17:28:12 [crit] 31#31: *1 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 17:28:13 [crit] 31#31: *1 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 17:39:31 [crit] 31#31: *17 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 17:39:31 [crit] 31#31: *17 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 17:39:31 [crit] 31#31: *17 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 17:39:31 [crit] 31#31: *17 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 17:39:32 [crit] 31#31: *17 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 17:39:32 [crit] 31#31: *17 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 17:39:32 [crit] 31#31: *17 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 17:39:32 [crit] 31#31: *17 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 17:39:32 [crit] 31#31: *17 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 17:39:32 [crit] 31#31: *17 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 17:44:36 [crit] 31#31: *29 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 17:44:36 [crit] 31#31: *29 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:24 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:24 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:25 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:25 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:25 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:25 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:25 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:25 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:25 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:25 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:25 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:25 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:26 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:26 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:26 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:26 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:26 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:26 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:26 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:26 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:26 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:26 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:26 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:26 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:27 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:27 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:27 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:27 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:27 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:27 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:27 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:27 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:27 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:27 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:27 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:27 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:28 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:28 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:28 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:28 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:28 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:28 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:28 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:28 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:28 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:28 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:28 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:28 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:29 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:29 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:29 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:29 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:29 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:29 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:29 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:29 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:29 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:29 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:29 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:29 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:30 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:30 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:30 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:30 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:30 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:30 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:09:30 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:09:30 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:10:19 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:10:19 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:10:20 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:10:20 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:10:20 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:10:20 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:10:20 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:10:20 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:10:20 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:10:20 [crit] 31#31: *37 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:21:54 [crit] 31#31: *117 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:21:54 [crit] 31#31: *117 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:21:55 [crit] 31#31: *117 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:21:55 [crit] 31#31: *117 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:21:55 [crit] 31#31: *117 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:21:55 [crit] 31#31: *117 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:21:55 [crit] 31#31: *117 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:21:55 [crit] 31#31: *117 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:21:55 [crit] 31#31: *117 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:21:55 [crit] 31#31: *117 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:21:55 [crit] 31#31: *117 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:21:56 [crit] 31#31: *117 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:21:56 [crit] 31#31: *117 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:21:56 [crit] 31#31: *117 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:21:56 [crit] 31#31: *117 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:21:56 [crit] 31#31: *117 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:21:56 [crit] 31#31: *117 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:21:56 [crit] 31#31: *117 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:21:56 [crit] 31#31: *117 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:21:56 [crit] 31#31: *117 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:32:33 [crit] 31#31: *139 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 212.2.243.64, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "3.34.255.93"
2021/03/24 18:34:24 [crit] 31#31: *142 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:34:24 [crit] 31#31: *142 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:34:25 [crit] 31#31: *142 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:34:25 [crit] 31#31: *142 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:34:25 [crit] 31#31: *142 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:34:25 [crit] 31#31: *142 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:34:26 [crit] 31#31: *142 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:34:26 [crit] 31#31: *142 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:40:30 [crit] 31#31: *151 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:40:30 [crit] 31#31: *151 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:40:30 [crit] 31#31: *151 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:40:30 [crit] 31#31: *151 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:40:31 [crit] 31#31: *151 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:40:31 [crit] 31#31: *151 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:40:45 [crit] 31#31: *151 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:40:46 [crit] 31#31: *151 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:41:56 [crit] 31#31: *161 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:41:56 [crit] 31#31: *161 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:41:57 [crit] 31#31: *161 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io"
2021/03/24 18:41:57 [crit] 31#31: *161 connect() to unix:/srv/docke-django/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 59.151.197.26, server: localhos, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/srv/docke-django/apps.sock:", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/"
2021/03/24 18:47:12 [error] 34#34: *2 open() "/srv/docker-django/.static/admin/css/base.css" failed (2: No such file or directory), client: 59.151.197.26, server: localhost, request: "GET /static/admin/css/base.css HTTP/1.1", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/admin/login/?next=/admin/"
2021/03/24 18:47:12 [error] 34#34: *1 open() "/srv/docker-django/.static/admin/css/nav_sidebar.css" failed (2: No such file or directory), client: 59.151.197.26, server: localhost, request: "GET /static/admin/css/nav_sidebar.css HTTP/1.1", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/admin/login/?next=/admin/"
2021/03/24 18:47:12 [error] 34#34: *9 open() "/srv/docker-django/.static/admin/css/responsive.css" failed (2: No such file or directory), client: 59.151.197.26, server: localhost, request: "GET /static/admin/css/responsive.css HTTP/1.1", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/admin/login/?next=/admin/"
2021/03/24 18:47:12 [error] 34#34: *10 open() "/srv/docker-django/.static/admin/css/login.css" failed (2: No such file or directory), client: 59.151.197.26, server: localhost, request: "GET /static/admin/css/login.css HTTP/1.1", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/admin/login/?next=/admin/"
2021/03/24 18:47:12 [error] 34#34: *2 open() "/srv/docker-django/.static/admin/js/nav_sidebar.js" failed (2: No such file or directory), client: 59.151.197.26, server: localhost, request: "GET /static/admin/js/nav_sidebar.js HTTP/1.1", host: "j4d104.p.ssafy.io", referrer: "http://j4d104.p.ssafy.io/admin/login/?next=/admin/"
2021/03/25 02:13:01 [error] 31#31: *25 open() "/srv/docker-django/.static/admin/css/nav_sidebar.css" failed (2: No such file or directory), client: 59.151.197.26, server: localhost, request: "GET /static/admin/css/nav_sidebar.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/25 02:13:01 [error] 31#31: *26 open() "/srv/docker-django/.static/admin/css/base.css" failed (2: No such file or directory), client: 59.151.197.26, server: localhost, request: "GET /static/admin/css/base.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/25 02:13:02 [error] 31#31: *31 open() "/srv/docker-django/.static/admin/css/login.css" failed (2: No such file or directory), client: 59.151.197.26, server: localhost, request: "GET /static/admin/css/login.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/25 02:13:02 [error] 31#31: *26 open() "/srv/docker-django/.static/admin/css/responsive.css" failed (2: No such file or directory), client: 59.151.197.26, server: localhost, request: "GET /static/admin/css/responsive.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/25 02:13:02 [error] 31#31: *25 open() "/srv/docker-django/.static/admin/js/nav_sidebar.js" failed (2: No such file or directory), client: 59.151.197.26, server: localhost, request: "GET /static/admin/js/nav_sidebar.js HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/26 01:40:40 [error] 27#27: *15 open() "/srv/docker-django/.static/admin/css/base.css" failed (2: No such file or directory), client: 59.151.197.26, server: localhost, request: "GET /static/admin/css/base.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/26 01:40:40 [error] 27#27: *16 open() "/srv/docker-django/.static/admin/css/nav_sidebar.css" failed (2: No such file or directory), client: 59.151.197.26, server: localhost, request: "GET /static/admin/css/nav_sidebar.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/26 01:40:40 [error] 27#27: *25 open() "/srv/docker-django/.static/admin/css/login.css" failed (2: No such file or directory), client: 59.151.197.26, server: localhost, request: "GET /static/admin/css/login.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/26 01:40:40 [error] 27#27: *15 open() "/srv/docker-django/.static/admin/css/responsive.css" failed (2: No such file or directory), client: 59.151.197.26, server: localhost, request: "GET /static/admin/css/responsive.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/26 01:40:40 [error] 27#27: *26 open() "/srv/docker-django/.static/admin/js/nav_sidebar.js" failed (2: No such file or directory), client: 59.151.197.26, server: localhost, request: "GET /static/admin/js/nav_sidebar.js HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/26 06:04:50 [error] 27#27: *58 open() "/srv/docker-django/.static/admin/css/base.css" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/admin/css/base.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/26 06:04:50 [error] 27#27: *59 open() "/srv/docker-django/.static/admin/css/nav_sidebar.css" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/admin/css/nav_sidebar.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/26 06:04:50 [error] 27#27: *63 open() "/srv/docker-django/.static/admin/css/login.css" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/admin/css/login.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/26 06:04:50 [error] 27#27: *64 open() "/srv/docker-django/.static/admin/css/responsive.css" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/admin/css/responsive.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/26 06:04:50 [error] 27#27: *58 open() "/srv/docker-django/.static/admin/js/nav_sidebar.js" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/admin/js/nav_sidebar.js HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/26 07:06:28 [notice] 78#78: signal process started
2021/03/26 07:09:49 [notice] 89#89: signal process started
2021/03/26 07:12:08 [notice] 96#96: signal process started
2021/03/26 07:12:48 [error] 98#98: *122 open() "/srv/docker-django/.static/rest_framework/css/bootstrap.min.css" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/community/"
2021/03/26 07:12:48 [error] 97#97: *121 open() "/srv/docker-django/.static/rest_framework/css/bootstrap-tweaks.css" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/community/"
2021/03/26 07:12:48 [error] 97#97: *124 open() "/srv/docker-django/.static/rest_framework/css/prettify.css" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/rest_framework/css/prettify.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/community/"
2021/03/26 07:12:48 [error] 98#98: *122 open() "/srv/docker-django/.static/rest_framework/css/default.css" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/rest_framework/css/default.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/community/"
2021/03/26 07:12:48 [error] 97#97: *126 open() "/srv/docker-django/.static/rest_framework/js/ajax-form.js" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/rest_framework/js/ajax-form.js HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/community/"
2021/03/26 07:12:48 [error] 97#97: *127 open() "/srv/docker-django/.static/rest_framework/js/jquery-3.5.1.min.js" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/community/"
2021/03/26 07:12:48 [error] 97#97: *125 open() "/srv/docker-django/.static/rest_framework/js/csrf.js" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/rest_framework/js/csrf.js HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/community/"
2021/03/26 07:12:48 [error] 97#97: *121 open() "/srv/docker-django/.static/rest_framework/js/bootstrap.min.js" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/community/"
2021/03/26 07:12:48 [error] 98#98: *122 open() "/srv/docker-django/.static/rest_framework/js/default.js" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/rest_framework/js/default.js HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/community/"
2021/03/26 07:12:48 [error] 97#97: *124 open() "/srv/docker-django/.static/rest_framework/js/prettify-min.js" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/rest_framework/js/prettify-min.js HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/community/"
2021/03/26 07:12:48 [error] 98#98: *122 open() "/srv/docker-django/.static/rest_framework/js/bootstrap.min.js" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/community/"
2021/03/26 07:12:48 [error] 98#98: *122 open() "/srv/docker-django/.static/rest_framework/js/prettify-min.js" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/rest_framework/js/prettify-min.js HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/community/"
2021/03/26 07:12:48 [error] 98#98: *122 open() "/srv/docker-django/.static/rest_framework/js/default.js" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/rest_framework/js/default.js HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/community/"
2021/03/26 07:13:08 [error] 97#97: *125 open() "/srv/docker-django/.static/admin/css/login.css" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/admin/css/login.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/26 07:13:08 [error] 98#98: *122 open() "/srv/docker-django/.static/admin/css/base.css" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/admin/css/base.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/26 07:13:08 [error] 97#97: *124 open() "/srv/docker-django/.static/admin/css/nav_sidebar.css" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/admin/css/nav_sidebar.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/26 07:13:08 [error] 97#97: *121 open() "/srv/docker-django/.static/admin/css/responsive.css" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/admin/css/responsive.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/26 07:13:08 [error] 97#97: *126 open() "/srv/docker-django/.static/admin/js/nav_sidebar.js" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/admin/js/nav_sidebar.js HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/26 07:23:35 [error] 97#97: *132 open() "/srv/docker-django/.static/admin/css/base.css" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/admin/css/base.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/26 07:23:35 [error] 97#97: *134 open() "/srv/docker-django/.static/admin/css/nav_sidebar.css" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/admin/css/nav_sidebar.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/26 07:23:35 [error] 97#97: *132 open() "/srv/docker-django/.static/admin/css/login.css" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/admin/css/login.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/26 07:23:35 [error] 97#97: *137 open() "/srv/docker-django/.static/admin/css/responsive.css" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/admin/css/responsive.css HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
2021/03/26 07:23:35 [error] 97#97: *134 open() "/srv/docker-django/.static/admin/js/nav_sidebar.js" failed (2: No such file or directory), client: 59.23.1.93, server: localhost, request: "GET /static/admin/js/nav_sidebar.js HTTP/1.1", host: "j4d104.p.ssafy.io:8080", referrer: "http://j4d104.p.ssafy.io:8080/admin/login/?next=/admin/"
